// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device_feature.proto

package GrpcDeviceFeature;

public final class DeviceFeatureOuterClass {
  private DeviceFeatureOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code GrpcDeviceFeature.CommandType}
   */
  public enum CommandType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Unknown = 0;</code>
     */
    Unknown(0),
    /**
     * <code>Keepalive = 1;</code>
     */
    Keepalive(1),
    /**
     * <code>Catalog = 2;</code>
     */
    Catalog(2),
    /**
     * <code>Play = 3;</code>
     */
    Play(3),
    /**
     * <code>Playback = 4;</code>
     */
    Playback(4),
    /**
     * <code>DeviceControl = 5;</code>
     */
    DeviceControl(5),
    /**
     * <code>Alarm = 6;</code>
     */
    Alarm(6),
    /**
     * <code>DeviceInfo = 7;</code>
     */
    DeviceInfo(7),
    /**
     * <code>DeviceStatus = 8;</code>
     */
    DeviceStatus(8),
    /**
     * <code>RecordInfo = 9;</code>
     */
    RecordInfo(9),
    /**
     * <code>Download = 10;</code>
     */
    Download(10),
    /**
     * <code>ConfigDownload = 11;</code>
     */
    ConfigDownload(11),
    /**
     * <code>Broadcast = 12;</code>
     */
    Broadcast(12),
    /**
     * <code>PresetQuery = 13;</code>
     */
    PresetQuery(13),
    /**
     * <code>MobilePosition = 14;</code>
     */
    MobilePosition(14),
    /**
     * <code>DeviceConfig = 15;</code>
     */
    DeviceConfig(15),
    /**
     * <code>MediaStatus = 16;</code>
     */
    MediaStatus(16),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Unknown = 0;</code>
     */
    public static final int Unknown_VALUE = 0;
    /**
     * <code>Keepalive = 1;</code>
     */
    public static final int Keepalive_VALUE = 1;
    /**
     * <code>Catalog = 2;</code>
     */
    public static final int Catalog_VALUE = 2;
    /**
     * <code>Play = 3;</code>
     */
    public static final int Play_VALUE = 3;
    /**
     * <code>Playback = 4;</code>
     */
    public static final int Playback_VALUE = 4;
    /**
     * <code>DeviceControl = 5;</code>
     */
    public static final int DeviceControl_VALUE = 5;
    /**
     * <code>Alarm = 6;</code>
     */
    public static final int Alarm_VALUE = 6;
    /**
     * <code>DeviceInfo = 7;</code>
     */
    public static final int DeviceInfo_VALUE = 7;
    /**
     * <code>DeviceStatus = 8;</code>
     */
    public static final int DeviceStatus_VALUE = 8;
    /**
     * <code>RecordInfo = 9;</code>
     */
    public static final int RecordInfo_VALUE = 9;
    /**
     * <code>Download = 10;</code>
     */
    public static final int Download_VALUE = 10;
    /**
     * <code>ConfigDownload = 11;</code>
     */
    public static final int ConfigDownload_VALUE = 11;
    /**
     * <code>Broadcast = 12;</code>
     */
    public static final int Broadcast_VALUE = 12;
    /**
     * <code>PresetQuery = 13;</code>
     */
    public static final int PresetQuery_VALUE = 13;
    /**
     * <code>MobilePosition = 14;</code>
     */
    public static final int MobilePosition_VALUE = 14;
    /**
     * <code>DeviceConfig = 15;</code>
     */
    public static final int DeviceConfig_VALUE = 15;
    /**
     * <code>MediaStatus = 16;</code>
     */
    public static final int MediaStatus_VALUE = 16;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CommandType valueOf(int value) {
      return forNumber(value);
    }

    public static CommandType forNumber(int value) {
      switch (value) {
        case 0: return Unknown;
        case 1: return Keepalive;
        case 2: return Catalog;
        case 3: return Play;
        case 4: return Playback;
        case 5: return DeviceControl;
        case 6: return Alarm;
        case 7: return DeviceInfo;
        case 8: return DeviceStatus;
        case 9: return RecordInfo;
        case 10: return Download;
        case 11: return ConfigDownload;
        case 12: return Broadcast;
        case 13: return PresetQuery;
        case 14: return MobilePosition;
        case 15: return DeviceConfig;
        case 16: return MediaStatus;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CommandType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
            public CommandType findValueByNumber(int number) {
              return CommandType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return GrpcDeviceFeature.DeviceFeatureOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final CommandType[] VALUES = values();

    public static CommandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CommandType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GrpcDeviceFeature.CommandType)
  }

  public interface DeviceStateQueryRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GrpcDeviceFeature.DeviceStateQueryRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string deviceid = 1;</code>
     */
    java.lang.String getDeviceid();
    /**
     * <code>string deviceid = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceidBytes();
  }
  /**
   * <pre>
   * The request message.
   * </pre>
   *
   * Protobuf type {@code GrpcDeviceFeature.DeviceStateQueryRequest}
   */
  public  static final class DeviceStateQueryRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GrpcDeviceFeature.DeviceStateQueryRequest)
      DeviceStateQueryRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeviceStateQueryRequest.newBuilder() to construct.
    private DeviceStateQueryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeviceStateQueryRequest() {
      deviceid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceStateQueryRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceid_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GrpcDeviceFeature.DeviceFeatureOuterClass.internal_static_GrpcDeviceFeature_DeviceStateQueryRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GrpcDeviceFeature.DeviceFeatureOuterClass.internal_static_GrpcDeviceFeature_DeviceStateQueryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest.class, GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest.Builder.class);
    }

    public static final int DEVICEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object deviceid_;
    /**
     * <code>string deviceid = 1;</code>
     */
    public java.lang.String getDeviceid() {
      java.lang.Object ref = deviceid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceid_ = s;
        return s;
      }
    }
    /**
     * <code>string deviceid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceidBytes() {
      java.lang.Object ref = deviceid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDeviceidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceid_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest)) {
        return super.equals(obj);
      }
      GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest other = (GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest) obj;

      boolean result = true;
      result = result && getDeviceid()
          .equals(other.getDeviceid());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The request message.
     * </pre>
     *
     * Protobuf type {@code GrpcDeviceFeature.DeviceStateQueryRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GrpcDeviceFeature.DeviceStateQueryRequest)
        GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GrpcDeviceFeature.DeviceFeatureOuterClass.internal_static_GrpcDeviceFeature_DeviceStateQueryRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GrpcDeviceFeature.DeviceFeatureOuterClass.internal_static_GrpcDeviceFeature_DeviceStateQueryRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest.class, GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest.Builder.class);
      }

      // Construct using GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        deviceid_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GrpcDeviceFeature.DeviceFeatureOuterClass.internal_static_GrpcDeviceFeature_DeviceStateQueryRequest_descriptor;
      }

      public GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest getDefaultInstanceForType() {
        return GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest.getDefaultInstance();
      }

      public GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest build() {
        GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest buildPartial() {
        GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest result = new GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest(this);
        result.deviceid_ = deviceid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest) {
          return mergeFrom((GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest other) {
        if (other == GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest.getDefaultInstance()) return this;
        if (!other.getDeviceid().isEmpty()) {
          deviceid_ = other.deviceid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object deviceid_ = "";
      /**
       * <code>string deviceid = 1;</code>
       */
      public java.lang.String getDeviceid() {
        java.lang.Object ref = deviceid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string deviceid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceidBytes() {
        java.lang.Object ref = deviceid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deviceid = 1;</code>
       */
      public Builder setDeviceid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deviceid = 1;</code>
       */
      public Builder clearDeviceid() {
        
        deviceid_ = getDefaultInstance().getDeviceid();
        onChanged();
        return this;
      }
      /**
       * <code>string deviceid = 1;</code>
       */
      public Builder setDeviceidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceid_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GrpcDeviceFeature.DeviceStateQueryRequest)
    }

    // @@protoc_insertion_point(class_scope:GrpcDeviceFeature.DeviceStateQueryRequest)
    private static final GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest();
    }

    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeviceStateQueryRequest>
        PARSER = new com.google.protobuf.AbstractParser<DeviceStateQueryRequest>() {
      public DeviceStateQueryRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceStateQueryRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeviceStateQueryRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceStateQueryRequest> getParserForType() {
      return PARSER;
    }

    public GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DeviceStateQueryReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GrpcDeviceFeature.DeviceStateQueryReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.GrpcDeviceFeature.Instance DeviceStatus = 1;</code>
     */
    boolean hasDeviceStatus();
    /**
     * <code>.GrpcDeviceFeature.Instance DeviceStatus = 1;</code>
     */
    GrpcDeviceFeature.DeviceFeatureOuterClass.Instance getDeviceStatus();
    /**
     * <code>.GrpcDeviceFeature.Instance DeviceStatus = 1;</code>
     */
    GrpcDeviceFeature.DeviceFeatureOuterClass.InstanceOrBuilder getDeviceStatusOrBuilder();
  }
  /**
   * <pre>
   * The response message.
   * </pre>
   *
   * Protobuf type {@code GrpcDeviceFeature.DeviceStateQueryReply}
   */
  public  static final class DeviceStateQueryReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GrpcDeviceFeature.DeviceStateQueryReply)
      DeviceStateQueryReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeviceStateQueryReply.newBuilder() to construct.
    private DeviceStateQueryReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeviceStateQueryReply() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceStateQueryReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              GrpcDeviceFeature.DeviceFeatureOuterClass.Instance.Builder subBuilder = null;
              if (deviceStatus_ != null) {
                subBuilder = deviceStatus_.toBuilder();
              }
              deviceStatus_ = input.readMessage(GrpcDeviceFeature.DeviceFeatureOuterClass.Instance.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(deviceStatus_);
                deviceStatus_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GrpcDeviceFeature.DeviceFeatureOuterClass.internal_static_GrpcDeviceFeature_DeviceStateQueryReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GrpcDeviceFeature.DeviceFeatureOuterClass.internal_static_GrpcDeviceFeature_DeviceStateQueryReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply.class, GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply.Builder.class);
    }

    public static final int DEVICESTATUS_FIELD_NUMBER = 1;
    private GrpcDeviceFeature.DeviceFeatureOuterClass.Instance deviceStatus_;
    /**
     * <code>.GrpcDeviceFeature.Instance DeviceStatus = 1;</code>
     */
    public boolean hasDeviceStatus() {
      return deviceStatus_ != null;
    }
    /**
     * <code>.GrpcDeviceFeature.Instance DeviceStatus = 1;</code>
     */
    public GrpcDeviceFeature.DeviceFeatureOuterClass.Instance getDeviceStatus() {
      return deviceStatus_ == null ? GrpcDeviceFeature.DeviceFeatureOuterClass.Instance.getDefaultInstance() : deviceStatus_;
    }
    /**
     * <code>.GrpcDeviceFeature.Instance DeviceStatus = 1;</code>
     */
    public GrpcDeviceFeature.DeviceFeatureOuterClass.InstanceOrBuilder getDeviceStatusOrBuilder() {
      return getDeviceStatus();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (deviceStatus_ != null) {
        output.writeMessage(1, getDeviceStatus());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (deviceStatus_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDeviceStatus());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply)) {
        return super.equals(obj);
      }
      GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply other = (GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply) obj;

      boolean result = true;
      result = result && (hasDeviceStatus() == other.hasDeviceStatus());
      if (hasDeviceStatus()) {
        result = result && getDeviceStatus()
            .equals(other.getDeviceStatus());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDeviceStatus()) {
        hash = (37 * hash) + DEVICESTATUS_FIELD_NUMBER;
        hash = (53 * hash) + getDeviceStatus().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The response message.
     * </pre>
     *
     * Protobuf type {@code GrpcDeviceFeature.DeviceStateQueryReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GrpcDeviceFeature.DeviceStateQueryReply)
        GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GrpcDeviceFeature.DeviceFeatureOuterClass.internal_static_GrpcDeviceFeature_DeviceStateQueryReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GrpcDeviceFeature.DeviceFeatureOuterClass.internal_static_GrpcDeviceFeature_DeviceStateQueryReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply.class, GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply.Builder.class);
      }

      // Construct using GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (deviceStatusBuilder_ == null) {
          deviceStatus_ = null;
        } else {
          deviceStatus_ = null;
          deviceStatusBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GrpcDeviceFeature.DeviceFeatureOuterClass.internal_static_GrpcDeviceFeature_DeviceStateQueryReply_descriptor;
      }

      public GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply getDefaultInstanceForType() {
        return GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply.getDefaultInstance();
      }

      public GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply build() {
        GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply buildPartial() {
        GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply result = new GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply(this);
        if (deviceStatusBuilder_ == null) {
          result.deviceStatus_ = deviceStatus_;
        } else {
          result.deviceStatus_ = deviceStatusBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply) {
          return mergeFrom((GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply other) {
        if (other == GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply.getDefaultInstance()) return this;
        if (other.hasDeviceStatus()) {
          mergeDeviceStatus(other.getDeviceStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private GrpcDeviceFeature.DeviceFeatureOuterClass.Instance deviceStatus_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          GrpcDeviceFeature.DeviceFeatureOuterClass.Instance, GrpcDeviceFeature.DeviceFeatureOuterClass.Instance.Builder, GrpcDeviceFeature.DeviceFeatureOuterClass.InstanceOrBuilder> deviceStatusBuilder_;
      /**
       * <code>.GrpcDeviceFeature.Instance DeviceStatus = 1;</code>
       */
      public boolean hasDeviceStatus() {
        return deviceStatusBuilder_ != null || deviceStatus_ != null;
      }
      /**
       * <code>.GrpcDeviceFeature.Instance DeviceStatus = 1;</code>
       */
      public GrpcDeviceFeature.DeviceFeatureOuterClass.Instance getDeviceStatus() {
        if (deviceStatusBuilder_ == null) {
          return deviceStatus_ == null ? GrpcDeviceFeature.DeviceFeatureOuterClass.Instance.getDefaultInstance() : deviceStatus_;
        } else {
          return deviceStatusBuilder_.getMessage();
        }
      }
      /**
       * <code>.GrpcDeviceFeature.Instance DeviceStatus = 1;</code>
       */
      public Builder setDeviceStatus(GrpcDeviceFeature.DeviceFeatureOuterClass.Instance value) {
        if (deviceStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deviceStatus_ = value;
          onChanged();
        } else {
          deviceStatusBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.GrpcDeviceFeature.Instance DeviceStatus = 1;</code>
       */
      public Builder setDeviceStatus(
          GrpcDeviceFeature.DeviceFeatureOuterClass.Instance.Builder builderForValue) {
        if (deviceStatusBuilder_ == null) {
          deviceStatus_ = builderForValue.build();
          onChanged();
        } else {
          deviceStatusBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.GrpcDeviceFeature.Instance DeviceStatus = 1;</code>
       */
      public Builder mergeDeviceStatus(GrpcDeviceFeature.DeviceFeatureOuterClass.Instance value) {
        if (deviceStatusBuilder_ == null) {
          if (deviceStatus_ != null) {
            deviceStatus_ =
              GrpcDeviceFeature.DeviceFeatureOuterClass.Instance.newBuilder(deviceStatus_).mergeFrom(value).buildPartial();
          } else {
            deviceStatus_ = value;
          }
          onChanged();
        } else {
          deviceStatusBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.GrpcDeviceFeature.Instance DeviceStatus = 1;</code>
       */
      public Builder clearDeviceStatus() {
        if (deviceStatusBuilder_ == null) {
          deviceStatus_ = null;
          onChanged();
        } else {
          deviceStatus_ = null;
          deviceStatusBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.GrpcDeviceFeature.Instance DeviceStatus = 1;</code>
       */
      public GrpcDeviceFeature.DeviceFeatureOuterClass.Instance.Builder getDeviceStatusBuilder() {
        
        onChanged();
        return getDeviceStatusFieldBuilder().getBuilder();
      }
      /**
       * <code>.GrpcDeviceFeature.Instance DeviceStatus = 1;</code>
       */
      public GrpcDeviceFeature.DeviceFeatureOuterClass.InstanceOrBuilder getDeviceStatusOrBuilder() {
        if (deviceStatusBuilder_ != null) {
          return deviceStatusBuilder_.getMessageOrBuilder();
        } else {
          return deviceStatus_ == null ?
              GrpcDeviceFeature.DeviceFeatureOuterClass.Instance.getDefaultInstance() : deviceStatus_;
        }
      }
      /**
       * <code>.GrpcDeviceFeature.Instance DeviceStatus = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GrpcDeviceFeature.DeviceFeatureOuterClass.Instance, GrpcDeviceFeature.DeviceFeatureOuterClass.Instance.Builder, GrpcDeviceFeature.DeviceFeatureOuterClass.InstanceOrBuilder> 
          getDeviceStatusFieldBuilder() {
        if (deviceStatusBuilder_ == null) {
          deviceStatusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GrpcDeviceFeature.DeviceFeatureOuterClass.Instance, GrpcDeviceFeature.DeviceFeatureOuterClass.Instance.Builder, GrpcDeviceFeature.DeviceFeatureOuterClass.InstanceOrBuilder>(
                  getDeviceStatus(),
                  getParentForChildren(),
                  isClean());
          deviceStatus_ = null;
        }
        return deviceStatusBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GrpcDeviceFeature.DeviceStateQueryReply)
    }

    // @@protoc_insertion_point(class_scope:GrpcDeviceFeature.DeviceStateQueryReply)
    private static final GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply();
    }

    public static GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeviceStateQueryReply>
        PARSER = new com.google.protobuf.AbstractParser<DeviceStateQueryReply>() {
      public DeviceStateQueryReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceStateQueryReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeviceStateQueryReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceStateQueryReply> getParserForType() {
      return PARSER;
    }

    public GrpcDeviceFeature.DeviceFeatureOuterClass.DeviceStateQueryReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InstanceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GrpcDeviceFeature.Instance)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.GrpcDeviceFeature.CommandType CmdType = 1;</code>
     */
    int getCmdTypeValue();
    /**
     * <code>.GrpcDeviceFeature.CommandType CmdType = 1;</code>
     */
    GrpcDeviceFeature.DeviceFeatureOuterClass.CommandType getCmdType();

    /**
     * <code>int32 SN = 2;</code>
     */
    int getSN();

    /**
     * <code>string DeviceID = 3;</code>
     */
    java.lang.String getDeviceID();
    /**
     * <code>string DeviceID = 3;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIDBytes();

    /**
     * <code>string Result = 4;</code>
     */
    java.lang.String getResult();
    /**
     * <code>string Result = 4;</code>
     */
    com.google.protobuf.ByteString
        getResultBytes();

    /**
     * <code>string Online = 5;</code>
     */
    java.lang.String getOnline();
    /**
     * <code>string Online = 5;</code>
     */
    com.google.protobuf.ByteString
        getOnlineBytes();

    /**
     * <code>string Status = 6;</code>
     */
    java.lang.String getStatus();
    /**
     * <code>string Status = 6;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>string Reason = 7;</code>
     */
    java.lang.String getReason();
    /**
     * <code>string Reason = 7;</code>
     */
    com.google.protobuf.ByteString
        getReasonBytes();
  }
  /**
   * Protobuf type {@code GrpcDeviceFeature.Instance}
   */
  public  static final class Instance extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GrpcDeviceFeature.Instance)
      InstanceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Instance.newBuilder() to construct.
    private Instance(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Instance() {
      cmdType_ = 0;
      sN_ = 0;
      deviceID_ = "";
      result_ = "";
      online_ = "";
      status_ = "";
      reason_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Instance(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              cmdType_ = rawValue;
              break;
            }
            case 16: {

              sN_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceID_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              result_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              online_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              reason_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GrpcDeviceFeature.DeviceFeatureOuterClass.internal_static_GrpcDeviceFeature_Instance_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GrpcDeviceFeature.DeviceFeatureOuterClass.internal_static_GrpcDeviceFeature_Instance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GrpcDeviceFeature.DeviceFeatureOuterClass.Instance.class, GrpcDeviceFeature.DeviceFeatureOuterClass.Instance.Builder.class);
    }

    public static final int CMDTYPE_FIELD_NUMBER = 1;
    private int cmdType_;
    /**
     * <code>.GrpcDeviceFeature.CommandType CmdType = 1;</code>
     */
    public int getCmdTypeValue() {
      return cmdType_;
    }
    /**
     * <code>.GrpcDeviceFeature.CommandType CmdType = 1;</code>
     */
    public GrpcDeviceFeature.DeviceFeatureOuterClass.CommandType getCmdType() {
      GrpcDeviceFeature.DeviceFeatureOuterClass.CommandType result = GrpcDeviceFeature.DeviceFeatureOuterClass.CommandType.valueOf(cmdType_);
      return result == null ? GrpcDeviceFeature.DeviceFeatureOuterClass.CommandType.UNRECOGNIZED : result;
    }

    public static final int SN_FIELD_NUMBER = 2;
    private int sN_;
    /**
     * <code>int32 SN = 2;</code>
     */
    public int getSN() {
      return sN_;
    }

    public static final int DEVICEID_FIELD_NUMBER = 3;
    private volatile java.lang.Object deviceID_;
    /**
     * <code>string DeviceID = 3;</code>
     */
    public java.lang.String getDeviceID() {
      java.lang.Object ref = deviceID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceID_ = s;
        return s;
      }
    }
    /**
     * <code>string DeviceID = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIDBytes() {
      java.lang.Object ref = deviceID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULT_FIELD_NUMBER = 4;
    private volatile java.lang.Object result_;
    /**
     * <code>string Result = 4;</code>
     */
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        result_ = s;
        return s;
      }
    }
    /**
     * <code>string Result = 4;</code>
     */
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ONLINE_FIELD_NUMBER = 5;
    private volatile java.lang.Object online_;
    /**
     * <code>string Online = 5;</code>
     */
    public java.lang.String getOnline() {
      java.lang.Object ref = online_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        online_ = s;
        return s;
      }
    }
    /**
     * <code>string Online = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOnlineBytes() {
      java.lang.Object ref = online_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        online_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 6;
    private volatile java.lang.Object status_;
    /**
     * <code>string Status = 6;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string Status = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REASON_FIELD_NUMBER = 7;
    private volatile java.lang.Object reason_;
    /**
     * <code>string Reason = 7;</code>
     */
    public java.lang.String getReason() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reason_ = s;
        return s;
      }
    }
    /**
     * <code>string Reason = 7;</code>
     */
    public com.google.protobuf.ByteString
        getReasonBytes() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmdType_ != GrpcDeviceFeature.DeviceFeatureOuterClass.CommandType.Unknown.getNumber()) {
        output.writeEnum(1, cmdType_);
      }
      if (sN_ != 0) {
        output.writeInt32(2, sN_);
      }
      if (!getDeviceIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, deviceID_);
      }
      if (!getResultBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, result_);
      }
      if (!getOnlineBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, online_);
      }
      if (!getStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, status_);
      }
      if (!getReasonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, reason_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmdType_ != GrpcDeviceFeature.DeviceFeatureOuterClass.CommandType.Unknown.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, cmdType_);
      }
      if (sN_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sN_);
      }
      if (!getDeviceIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, deviceID_);
      }
      if (!getResultBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, result_);
      }
      if (!getOnlineBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, online_);
      }
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, status_);
      }
      if (!getReasonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, reason_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GrpcDeviceFeature.DeviceFeatureOuterClass.Instance)) {
        return super.equals(obj);
      }
      GrpcDeviceFeature.DeviceFeatureOuterClass.Instance other = (GrpcDeviceFeature.DeviceFeatureOuterClass.Instance) obj;

      boolean result = true;
      result = result && cmdType_ == other.cmdType_;
      result = result && (getSN()
          == other.getSN());
      result = result && getDeviceID()
          .equals(other.getDeviceID());
      result = result && getResult()
          .equals(other.getResult());
      result = result && getOnline()
          .equals(other.getOnline());
      result = result && getStatus()
          .equals(other.getStatus());
      result = result && getReason()
          .equals(other.getReason());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + cmdType_;
      hash = (37 * hash) + SN_FIELD_NUMBER;
      hash = (53 * hash) + getSN();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceID().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
      hash = (37 * hash) + ONLINE_FIELD_NUMBER;
      hash = (53 * hash) + getOnline().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (37 * hash) + REASON_FIELD_NUMBER;
      hash = (53 * hash) + getReason().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GrpcDeviceFeature.DeviceFeatureOuterClass.Instance parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.Instance parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.Instance parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.Instance parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.Instance parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.Instance parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.Instance parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.Instance parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.Instance parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.Instance parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.Instance parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrpcDeviceFeature.DeviceFeatureOuterClass.Instance parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GrpcDeviceFeature.DeviceFeatureOuterClass.Instance prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GrpcDeviceFeature.Instance}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GrpcDeviceFeature.Instance)
        GrpcDeviceFeature.DeviceFeatureOuterClass.InstanceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GrpcDeviceFeature.DeviceFeatureOuterClass.internal_static_GrpcDeviceFeature_Instance_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GrpcDeviceFeature.DeviceFeatureOuterClass.internal_static_GrpcDeviceFeature_Instance_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GrpcDeviceFeature.DeviceFeatureOuterClass.Instance.class, GrpcDeviceFeature.DeviceFeatureOuterClass.Instance.Builder.class);
      }

      // Construct using GrpcDeviceFeature.DeviceFeatureOuterClass.Instance.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cmdType_ = 0;

        sN_ = 0;

        deviceID_ = "";

        result_ = "";

        online_ = "";

        status_ = "";

        reason_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GrpcDeviceFeature.DeviceFeatureOuterClass.internal_static_GrpcDeviceFeature_Instance_descriptor;
      }

      public GrpcDeviceFeature.DeviceFeatureOuterClass.Instance getDefaultInstanceForType() {
        return GrpcDeviceFeature.DeviceFeatureOuterClass.Instance.getDefaultInstance();
      }

      public GrpcDeviceFeature.DeviceFeatureOuterClass.Instance build() {
        GrpcDeviceFeature.DeviceFeatureOuterClass.Instance result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GrpcDeviceFeature.DeviceFeatureOuterClass.Instance buildPartial() {
        GrpcDeviceFeature.DeviceFeatureOuterClass.Instance result = new GrpcDeviceFeature.DeviceFeatureOuterClass.Instance(this);
        result.cmdType_ = cmdType_;
        result.sN_ = sN_;
        result.deviceID_ = deviceID_;
        result.result_ = result_;
        result.online_ = online_;
        result.status_ = status_;
        result.reason_ = reason_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GrpcDeviceFeature.DeviceFeatureOuterClass.Instance) {
          return mergeFrom((GrpcDeviceFeature.DeviceFeatureOuterClass.Instance)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GrpcDeviceFeature.DeviceFeatureOuterClass.Instance other) {
        if (other == GrpcDeviceFeature.DeviceFeatureOuterClass.Instance.getDefaultInstance()) return this;
        if (other.cmdType_ != 0) {
          setCmdTypeValue(other.getCmdTypeValue());
        }
        if (other.getSN() != 0) {
          setSN(other.getSN());
        }
        if (!other.getDeviceID().isEmpty()) {
          deviceID_ = other.deviceID_;
          onChanged();
        }
        if (!other.getResult().isEmpty()) {
          result_ = other.result_;
          onChanged();
        }
        if (!other.getOnline().isEmpty()) {
          online_ = other.online_;
          onChanged();
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        if (!other.getReason().isEmpty()) {
          reason_ = other.reason_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GrpcDeviceFeature.DeviceFeatureOuterClass.Instance parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GrpcDeviceFeature.DeviceFeatureOuterClass.Instance) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cmdType_ = 0;
      /**
       * <code>.GrpcDeviceFeature.CommandType CmdType = 1;</code>
       */
      public int getCmdTypeValue() {
        return cmdType_;
      }
      /**
       * <code>.GrpcDeviceFeature.CommandType CmdType = 1;</code>
       */
      public Builder setCmdTypeValue(int value) {
        cmdType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.GrpcDeviceFeature.CommandType CmdType = 1;</code>
       */
      public GrpcDeviceFeature.DeviceFeatureOuterClass.CommandType getCmdType() {
        GrpcDeviceFeature.DeviceFeatureOuterClass.CommandType result = GrpcDeviceFeature.DeviceFeatureOuterClass.CommandType.valueOf(cmdType_);
        return result == null ? GrpcDeviceFeature.DeviceFeatureOuterClass.CommandType.UNRECOGNIZED : result;
      }
      /**
       * <code>.GrpcDeviceFeature.CommandType CmdType = 1;</code>
       */
      public Builder setCmdType(GrpcDeviceFeature.DeviceFeatureOuterClass.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cmdType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.GrpcDeviceFeature.CommandType CmdType = 1;</code>
       */
      public Builder clearCmdType() {
        
        cmdType_ = 0;
        onChanged();
        return this;
      }

      private int sN_ ;
      /**
       * <code>int32 SN = 2;</code>
       */
      public int getSN() {
        return sN_;
      }
      /**
       * <code>int32 SN = 2;</code>
       */
      public Builder setSN(int value) {
        
        sN_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 SN = 2;</code>
       */
      public Builder clearSN() {
        
        sN_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object deviceID_ = "";
      /**
       * <code>string DeviceID = 3;</code>
       */
      public java.lang.String getDeviceID() {
        java.lang.Object ref = deviceID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string DeviceID = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIDBytes() {
        java.lang.Object ref = deviceID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string DeviceID = 3;</code>
       */
      public Builder setDeviceID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string DeviceID = 3;</code>
       */
      public Builder clearDeviceID() {
        
        deviceID_ = getDefaultInstance().getDeviceID();
        onChanged();
        return this;
      }
      /**
       * <code>string DeviceID = 3;</code>
       */
      public Builder setDeviceIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object result_ = "";
      /**
       * <code>string Result = 4;</code>
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Result = 4;</code>
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Result = 4;</code>
       */
      public Builder setResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Result = 4;</code>
       */
      public Builder clearResult() {
        
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }
      /**
       * <code>string Result = 4;</code>
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        result_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object online_ = "";
      /**
       * <code>string Online = 5;</code>
       */
      public java.lang.String getOnline() {
        java.lang.Object ref = online_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          online_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Online = 5;</code>
       */
      public com.google.protobuf.ByteString
          getOnlineBytes() {
        java.lang.Object ref = online_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          online_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Online = 5;</code>
       */
      public Builder setOnline(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        online_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Online = 5;</code>
       */
      public Builder clearOnline() {
        
        online_ = getDefaultInstance().getOnline();
        onChanged();
        return this;
      }
      /**
       * <code>string Online = 5;</code>
       */
      public Builder setOnlineBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        online_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>string Status = 6;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Status = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Status = 6;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Status = 6;</code>
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string Status = 6;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        status_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reason_ = "";
      /**
       * <code>string Reason = 7;</code>
       */
      public java.lang.String getReason() {
        java.lang.Object ref = reason_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reason_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Reason = 7;</code>
       */
      public com.google.protobuf.ByteString
          getReasonBytes() {
        java.lang.Object ref = reason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Reason = 7;</code>
       */
      public Builder setReason(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Reason = 7;</code>
       */
      public Builder clearReason() {
        
        reason_ = getDefaultInstance().getReason();
        onChanged();
        return this;
      }
      /**
       * <code>string Reason = 7;</code>
       */
      public Builder setReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reason_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GrpcDeviceFeature.Instance)
    }

    // @@protoc_insertion_point(class_scope:GrpcDeviceFeature.Instance)
    private static final GrpcDeviceFeature.DeviceFeatureOuterClass.Instance DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GrpcDeviceFeature.DeviceFeatureOuterClass.Instance();
    }

    public static GrpcDeviceFeature.DeviceFeatureOuterClass.Instance getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Instance>
        PARSER = new com.google.protobuf.AbstractParser<Instance>() {
      public Instance parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Instance(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Instance> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Instance> getParserForType() {
      return PARSER;
    }

    public GrpcDeviceFeature.DeviceFeatureOuterClass.Instance getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcDeviceFeature_DeviceStateQueryRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcDeviceFeature_DeviceStateQueryRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcDeviceFeature_DeviceStateQueryReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcDeviceFeature_DeviceStateQueryReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcDeviceFeature_Instance_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcDeviceFeature_Instance_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024device_feature.proto\022\021GrpcDeviceFeatur" +
      "e\"+\n\027DeviceStateQueryRequest\022\020\n\010deviceid" +
      "\030\001 \001(\t\"J\n\025DeviceStateQueryReply\0221\n\014Devic" +
      "eStatus\030\001 \001(\0132\033.GrpcDeviceFeature.Instan" +
      "ce\"\231\001\n\010Instance\022/\n\007CmdType\030\001 \001(\0162\036.GrpcD" +
      "eviceFeature.CommandType\022\n\n\002SN\030\002 \001(\005\022\020\n\010" +
      "DeviceID\030\003 \001(\t\022\016\n\006Result\030\004 \001(\t\022\016\n\006Online" +
      "\030\005 \001(\t\022\016\n\006Status\030\006 \001(\t\022\016\n\006Reason\030\007 \001(\t*\227" +
      "\002\n\013CommandType\022\013\n\007Unknown\020\000\022\r\n\tKeepalive" +
      "\020\001\022\013\n\007Catalog\020\002\022\010\n\004Play\020\003\022\014\n\010Playback\020\004\022" +
      "\021\n\rDeviceControl\020\005\022\t\n\005Alarm\020\006\022\016\n\nDeviceI" +
      "nfo\020\007\022\020\n\014DeviceStatus\020\010\022\016\n\nRecordInfo\020\t\022" +
      "\014\n\010Download\020\n\022\022\n\016ConfigDownload\020\013\022\r\n\tBro" +
      "adcast\020\014\022\017\n\013PresetQuery\020\r\022\022\n\016MobilePosit" +
      "ion\020\016\022\020\n\014DeviceConfig\020\017\022\017\n\013MediaStatus\020\020" +
      "2{\n\rDeviceFeature\022j\n\020DeviceStateQuery\022*." +
      "GrpcDeviceFeature.DeviceStateQueryReques" +
      "t\032(.GrpcDeviceFeature.DeviceStateQueryRe" +
      "ply\"\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GrpcDeviceFeature_DeviceStateQueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GrpcDeviceFeature_DeviceStateQueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcDeviceFeature_DeviceStateQueryRequest_descriptor,
        new java.lang.String[] { "Deviceid", });
    internal_static_GrpcDeviceFeature_DeviceStateQueryReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GrpcDeviceFeature_DeviceStateQueryReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcDeviceFeature_DeviceStateQueryReply_descriptor,
        new java.lang.String[] { "DeviceStatus", });
    internal_static_GrpcDeviceFeature_Instance_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GrpcDeviceFeature_Instance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcDeviceFeature_Instance_descriptor,
        new java.lang.String[] { "CmdType", "SN", "DeviceID", "Result", "Online", "Status", "Reason", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
