// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptz_control.proto

package GrpcPtzControl;

public final class PtzControlOuterClass {
  private PtzControlOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PtzDirectRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GrpcPtzControl.PtzDirectRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.GrpcPtzControl.PtzXYZ xyz = 1;</code>
     */
    boolean hasXyz();
    /**
     * <code>.GrpcPtzControl.PtzXYZ xyz = 1;</code>
     */
    GrpcPtzControl.PtzControlOuterClass.PtzXYZ getXyz();
    /**
     * <code>.GrpcPtzControl.PtzXYZ xyz = 1;</code>
     */
    GrpcPtzControl.PtzControlOuterClass.PtzXYZOrBuilder getXyzOrBuilder();

    /**
     * <code>int32 speed = 2;</code>
     */
    int getSpeed();

    /**
     * <code>string deviceid = 3;</code>
     */
    java.lang.String getDeviceid();
    /**
     * <code>string deviceid = 3;</code>
     */
    com.google.protobuf.ByteString
        getDeviceidBytes();
  }
  /**
   * <pre>
   * The request message.
   * </pre>
   *
   * Protobuf type {@code GrpcPtzControl.PtzDirectRequest}
   */
  public  static final class PtzDirectRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GrpcPtzControl.PtzDirectRequest)
      PtzDirectRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PtzDirectRequest.newBuilder() to construct.
    private PtzDirectRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PtzDirectRequest() {
      speed_ = 0;
      deviceid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PtzDirectRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              GrpcPtzControl.PtzControlOuterClass.PtzXYZ.Builder subBuilder = null;
              if (xyz_ != null) {
                subBuilder = xyz_.toBuilder();
              }
              xyz_ = input.readMessage(GrpcPtzControl.PtzControlOuterClass.PtzXYZ.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(xyz_);
                xyz_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              speed_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceid_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GrpcPtzControl.PtzControlOuterClass.internal_static_GrpcPtzControl_PtzDirectRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GrpcPtzControl.PtzControlOuterClass.internal_static_GrpcPtzControl_PtzDirectRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest.class, GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest.Builder.class);
    }

    public static final int XYZ_FIELD_NUMBER = 1;
    private GrpcPtzControl.PtzControlOuterClass.PtzXYZ xyz_;
    /**
     * <code>.GrpcPtzControl.PtzXYZ xyz = 1;</code>
     */
    public boolean hasXyz() {
      return xyz_ != null;
    }
    /**
     * <code>.GrpcPtzControl.PtzXYZ xyz = 1;</code>
     */
    public GrpcPtzControl.PtzControlOuterClass.PtzXYZ getXyz() {
      return xyz_ == null ? GrpcPtzControl.PtzControlOuterClass.PtzXYZ.getDefaultInstance() : xyz_;
    }
    /**
     * <code>.GrpcPtzControl.PtzXYZ xyz = 1;</code>
     */
    public GrpcPtzControl.PtzControlOuterClass.PtzXYZOrBuilder getXyzOrBuilder() {
      return getXyz();
    }

    public static final int SPEED_FIELD_NUMBER = 2;
    private int speed_;
    /**
     * <code>int32 speed = 2;</code>
     */
    public int getSpeed() {
      return speed_;
    }

    public static final int DEVICEID_FIELD_NUMBER = 3;
    private volatile java.lang.Object deviceid_;
    /**
     * <code>string deviceid = 3;</code>
     */
    public java.lang.String getDeviceid() {
      java.lang.Object ref = deviceid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceid_ = s;
        return s;
      }
    }
    /**
     * <code>string deviceid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceidBytes() {
      java.lang.Object ref = deviceid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (xyz_ != null) {
        output.writeMessage(1, getXyz());
      }
      if (speed_ != 0) {
        output.writeInt32(2, speed_);
      }
      if (!getDeviceidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, deviceid_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (xyz_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getXyz());
      }
      if (speed_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, speed_);
      }
      if (!getDeviceidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, deviceid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest)) {
        return super.equals(obj);
      }
      GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest other = (GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest) obj;

      boolean result = true;
      result = result && (hasXyz() == other.hasXyz());
      if (hasXyz()) {
        result = result && getXyz()
            .equals(other.getXyz());
      }
      result = result && (getSpeed()
          == other.getSpeed());
      result = result && getDeviceid()
          .equals(other.getDeviceid());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasXyz()) {
        hash = (37 * hash) + XYZ_FIELD_NUMBER;
        hash = (53 * hash) + getXyz().hashCode();
      }
      hash = (37 * hash) + SPEED_FIELD_NUMBER;
      hash = (53 * hash) + getSpeed();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The request message.
     * </pre>
     *
     * Protobuf type {@code GrpcPtzControl.PtzDirectRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GrpcPtzControl.PtzDirectRequest)
        GrpcPtzControl.PtzControlOuterClass.PtzDirectRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GrpcPtzControl.PtzControlOuterClass.internal_static_GrpcPtzControl_PtzDirectRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GrpcPtzControl.PtzControlOuterClass.internal_static_GrpcPtzControl_PtzDirectRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest.class, GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest.Builder.class);
      }

      // Construct using GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (xyzBuilder_ == null) {
          xyz_ = null;
        } else {
          xyz_ = null;
          xyzBuilder_ = null;
        }
        speed_ = 0;

        deviceid_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GrpcPtzControl.PtzControlOuterClass.internal_static_GrpcPtzControl_PtzDirectRequest_descriptor;
      }

      public GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest getDefaultInstanceForType() {
        return GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest.getDefaultInstance();
      }

      public GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest build() {
        GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest buildPartial() {
        GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest result = new GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest(this);
        if (xyzBuilder_ == null) {
          result.xyz_ = xyz_;
        } else {
          result.xyz_ = xyzBuilder_.build();
        }
        result.speed_ = speed_;
        result.deviceid_ = deviceid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest) {
          return mergeFrom((GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest other) {
        if (other == GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest.getDefaultInstance()) return this;
        if (other.hasXyz()) {
          mergeXyz(other.getXyz());
        }
        if (other.getSpeed() != 0) {
          setSpeed(other.getSpeed());
        }
        if (!other.getDeviceid().isEmpty()) {
          deviceid_ = other.deviceid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private GrpcPtzControl.PtzControlOuterClass.PtzXYZ xyz_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          GrpcPtzControl.PtzControlOuterClass.PtzXYZ, GrpcPtzControl.PtzControlOuterClass.PtzXYZ.Builder, GrpcPtzControl.PtzControlOuterClass.PtzXYZOrBuilder> xyzBuilder_;
      /**
       * <code>.GrpcPtzControl.PtzXYZ xyz = 1;</code>
       */
      public boolean hasXyz() {
        return xyzBuilder_ != null || xyz_ != null;
      }
      /**
       * <code>.GrpcPtzControl.PtzXYZ xyz = 1;</code>
       */
      public GrpcPtzControl.PtzControlOuterClass.PtzXYZ getXyz() {
        if (xyzBuilder_ == null) {
          return xyz_ == null ? GrpcPtzControl.PtzControlOuterClass.PtzXYZ.getDefaultInstance() : xyz_;
        } else {
          return xyzBuilder_.getMessage();
        }
      }
      /**
       * <code>.GrpcPtzControl.PtzXYZ xyz = 1;</code>
       */
      public Builder setXyz(GrpcPtzControl.PtzControlOuterClass.PtzXYZ value) {
        if (xyzBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          xyz_ = value;
          onChanged();
        } else {
          xyzBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.GrpcPtzControl.PtzXYZ xyz = 1;</code>
       */
      public Builder setXyz(
          GrpcPtzControl.PtzControlOuterClass.PtzXYZ.Builder builderForValue) {
        if (xyzBuilder_ == null) {
          xyz_ = builderForValue.build();
          onChanged();
        } else {
          xyzBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.GrpcPtzControl.PtzXYZ xyz = 1;</code>
       */
      public Builder mergeXyz(GrpcPtzControl.PtzControlOuterClass.PtzXYZ value) {
        if (xyzBuilder_ == null) {
          if (xyz_ != null) {
            xyz_ =
              GrpcPtzControl.PtzControlOuterClass.PtzXYZ.newBuilder(xyz_).mergeFrom(value).buildPartial();
          } else {
            xyz_ = value;
          }
          onChanged();
        } else {
          xyzBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.GrpcPtzControl.PtzXYZ xyz = 1;</code>
       */
      public Builder clearXyz() {
        if (xyzBuilder_ == null) {
          xyz_ = null;
          onChanged();
        } else {
          xyz_ = null;
          xyzBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.GrpcPtzControl.PtzXYZ xyz = 1;</code>
       */
      public GrpcPtzControl.PtzControlOuterClass.PtzXYZ.Builder getXyzBuilder() {
        
        onChanged();
        return getXyzFieldBuilder().getBuilder();
      }
      /**
       * <code>.GrpcPtzControl.PtzXYZ xyz = 1;</code>
       */
      public GrpcPtzControl.PtzControlOuterClass.PtzXYZOrBuilder getXyzOrBuilder() {
        if (xyzBuilder_ != null) {
          return xyzBuilder_.getMessageOrBuilder();
        } else {
          return xyz_ == null ?
              GrpcPtzControl.PtzControlOuterClass.PtzXYZ.getDefaultInstance() : xyz_;
        }
      }
      /**
       * <code>.GrpcPtzControl.PtzXYZ xyz = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GrpcPtzControl.PtzControlOuterClass.PtzXYZ, GrpcPtzControl.PtzControlOuterClass.PtzXYZ.Builder, GrpcPtzControl.PtzControlOuterClass.PtzXYZOrBuilder> 
          getXyzFieldBuilder() {
        if (xyzBuilder_ == null) {
          xyzBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GrpcPtzControl.PtzControlOuterClass.PtzXYZ, GrpcPtzControl.PtzControlOuterClass.PtzXYZ.Builder, GrpcPtzControl.PtzControlOuterClass.PtzXYZOrBuilder>(
                  getXyz(),
                  getParentForChildren(),
                  isClean());
          xyz_ = null;
        }
        return xyzBuilder_;
      }

      private int speed_ ;
      /**
       * <code>int32 speed = 2;</code>
       */
      public int getSpeed() {
        return speed_;
      }
      /**
       * <code>int32 speed = 2;</code>
       */
      public Builder setSpeed(int value) {
        
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 speed = 2;</code>
       */
      public Builder clearSpeed() {
        
        speed_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object deviceid_ = "";
      /**
       * <code>string deviceid = 3;</code>
       */
      public java.lang.String getDeviceid() {
        java.lang.Object ref = deviceid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string deviceid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceidBytes() {
        java.lang.Object ref = deviceid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deviceid = 3;</code>
       */
      public Builder setDeviceid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deviceid = 3;</code>
       */
      public Builder clearDeviceid() {
        
        deviceid_ = getDefaultInstance().getDeviceid();
        onChanged();
        return this;
      }
      /**
       * <code>string deviceid = 3;</code>
       */
      public Builder setDeviceidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceid_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GrpcPtzControl.PtzDirectRequest)
    }

    // @@protoc_insertion_point(class_scope:GrpcPtzControl.PtzDirectRequest)
    private static final GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest();
    }

    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PtzDirectRequest>
        PARSER = new com.google.protobuf.AbstractParser<PtzDirectRequest>() {
      public PtzDirectRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PtzDirectRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PtzDirectRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PtzDirectRequest> getParserForType() {
      return PARSER;
    }

    public GrpcPtzControl.PtzControlOuterClass.PtzDirectRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PtzDirectReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GrpcPtzControl.PtzDirectReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * The response message.
   * </pre>
   *
   * Protobuf type {@code GrpcPtzControl.PtzDirectReply}
   */
  public  static final class PtzDirectReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GrpcPtzControl.PtzDirectReply)
      PtzDirectReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PtzDirectReply.newBuilder() to construct.
    private PtzDirectReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PtzDirectReply() {
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PtzDirectReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GrpcPtzControl.PtzControlOuterClass.internal_static_GrpcPtzControl_PtzDirectReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GrpcPtzControl.PtzControlOuterClass.internal_static_GrpcPtzControl_PtzDirectReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GrpcPtzControl.PtzControlOuterClass.PtzDirectReply.class, GrpcPtzControl.PtzControlOuterClass.PtzDirectReply.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GrpcPtzControl.PtzControlOuterClass.PtzDirectReply)) {
        return super.equals(obj);
      }
      GrpcPtzControl.PtzControlOuterClass.PtzDirectReply other = (GrpcPtzControl.PtzControlOuterClass.PtzDirectReply) obj;

      boolean result = true;
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GrpcPtzControl.PtzControlOuterClass.PtzDirectReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The response message.
     * </pre>
     *
     * Protobuf type {@code GrpcPtzControl.PtzDirectReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GrpcPtzControl.PtzDirectReply)
        GrpcPtzControl.PtzControlOuterClass.PtzDirectReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GrpcPtzControl.PtzControlOuterClass.internal_static_GrpcPtzControl_PtzDirectReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GrpcPtzControl.PtzControlOuterClass.internal_static_GrpcPtzControl_PtzDirectReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GrpcPtzControl.PtzControlOuterClass.PtzDirectReply.class, GrpcPtzControl.PtzControlOuterClass.PtzDirectReply.Builder.class);
      }

      // Construct using GrpcPtzControl.PtzControlOuterClass.PtzDirectReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        message_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GrpcPtzControl.PtzControlOuterClass.internal_static_GrpcPtzControl_PtzDirectReply_descriptor;
      }

      public GrpcPtzControl.PtzControlOuterClass.PtzDirectReply getDefaultInstanceForType() {
        return GrpcPtzControl.PtzControlOuterClass.PtzDirectReply.getDefaultInstance();
      }

      public GrpcPtzControl.PtzControlOuterClass.PtzDirectReply build() {
        GrpcPtzControl.PtzControlOuterClass.PtzDirectReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GrpcPtzControl.PtzControlOuterClass.PtzDirectReply buildPartial() {
        GrpcPtzControl.PtzControlOuterClass.PtzDirectReply result = new GrpcPtzControl.PtzControlOuterClass.PtzDirectReply(this);
        result.message_ = message_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GrpcPtzControl.PtzControlOuterClass.PtzDirectReply) {
          return mergeFrom((GrpcPtzControl.PtzControlOuterClass.PtzDirectReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GrpcPtzControl.PtzControlOuterClass.PtzDirectReply other) {
        if (other == GrpcPtzControl.PtzControlOuterClass.PtzDirectReply.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GrpcPtzControl.PtzControlOuterClass.PtzDirectReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GrpcPtzControl.PtzControlOuterClass.PtzDirectReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GrpcPtzControl.PtzDirectReply)
    }

    // @@protoc_insertion_point(class_scope:GrpcPtzControl.PtzDirectReply)
    private static final GrpcPtzControl.PtzControlOuterClass.PtzDirectReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GrpcPtzControl.PtzControlOuterClass.PtzDirectReply();
    }

    public static GrpcPtzControl.PtzControlOuterClass.PtzDirectReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PtzDirectReply>
        PARSER = new com.google.protobuf.AbstractParser<PtzDirectReply>() {
      public PtzDirectReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PtzDirectReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PtzDirectReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PtzDirectReply> getParserForType() {
      return PARSER;
    }

    public GrpcPtzControl.PtzControlOuterClass.PtzDirectReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PtzXYZOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GrpcPtzControl.PtzXYZ)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 X = 1;</code>
     */
    int getX();

    /**
     * <code>int32 Y = 2;</code>
     */
    int getY();

    /**
     * <code>int32 Z = 3;</code>
     */
    int getZ();
  }
  /**
   * Protobuf type {@code GrpcPtzControl.PtzXYZ}
   */
  public  static final class PtzXYZ extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GrpcPtzControl.PtzXYZ)
      PtzXYZOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PtzXYZ.newBuilder() to construct.
    private PtzXYZ(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PtzXYZ() {
      x_ = 0;
      y_ = 0;
      z_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PtzXYZ(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              x_ = input.readInt32();
              break;
            }
            case 16: {

              y_ = input.readInt32();
              break;
            }
            case 24: {

              z_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GrpcPtzControl.PtzControlOuterClass.internal_static_GrpcPtzControl_PtzXYZ_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GrpcPtzControl.PtzControlOuterClass.internal_static_GrpcPtzControl_PtzXYZ_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GrpcPtzControl.PtzControlOuterClass.PtzXYZ.class, GrpcPtzControl.PtzControlOuterClass.PtzXYZ.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>int32 X = 1;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>int32 Y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private int z_;
    /**
     * <code>int32 Z = 3;</code>
     */
    public int getZ() {
      return z_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0) {
        output.writeInt32(1, x_);
      }
      if (y_ != 0) {
        output.writeInt32(2, y_);
      }
      if (z_ != 0) {
        output.writeInt32(3, z_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      if (z_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, z_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GrpcPtzControl.PtzControlOuterClass.PtzXYZ)) {
        return super.equals(obj);
      }
      GrpcPtzControl.PtzControlOuterClass.PtzXYZ other = (GrpcPtzControl.PtzControlOuterClass.PtzXYZ) obj;

      boolean result = true;
      result = result && (getX()
          == other.getX());
      result = result && (getY()
          == other.getY());
      result = result && (getZ()
          == other.getZ());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY();
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + getZ();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GrpcPtzControl.PtzControlOuterClass.PtzXYZ parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzXYZ parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzXYZ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzXYZ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzXYZ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzXYZ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzXYZ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzXYZ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzXYZ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzXYZ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzXYZ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrpcPtzControl.PtzControlOuterClass.PtzXYZ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GrpcPtzControl.PtzControlOuterClass.PtzXYZ prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GrpcPtzControl.PtzXYZ}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GrpcPtzControl.PtzXYZ)
        GrpcPtzControl.PtzControlOuterClass.PtzXYZOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GrpcPtzControl.PtzControlOuterClass.internal_static_GrpcPtzControl_PtzXYZ_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GrpcPtzControl.PtzControlOuterClass.internal_static_GrpcPtzControl_PtzXYZ_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GrpcPtzControl.PtzControlOuterClass.PtzXYZ.class, GrpcPtzControl.PtzControlOuterClass.PtzXYZ.Builder.class);
      }

      // Construct using GrpcPtzControl.PtzControlOuterClass.PtzXYZ.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        x_ = 0;

        y_ = 0;

        z_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GrpcPtzControl.PtzControlOuterClass.internal_static_GrpcPtzControl_PtzXYZ_descriptor;
      }

      public GrpcPtzControl.PtzControlOuterClass.PtzXYZ getDefaultInstanceForType() {
        return GrpcPtzControl.PtzControlOuterClass.PtzXYZ.getDefaultInstance();
      }

      public GrpcPtzControl.PtzControlOuterClass.PtzXYZ build() {
        GrpcPtzControl.PtzControlOuterClass.PtzXYZ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GrpcPtzControl.PtzControlOuterClass.PtzXYZ buildPartial() {
        GrpcPtzControl.PtzControlOuterClass.PtzXYZ result = new GrpcPtzControl.PtzControlOuterClass.PtzXYZ(this);
        result.x_ = x_;
        result.y_ = y_;
        result.z_ = z_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GrpcPtzControl.PtzControlOuterClass.PtzXYZ) {
          return mergeFrom((GrpcPtzControl.PtzControlOuterClass.PtzXYZ)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GrpcPtzControl.PtzControlOuterClass.PtzXYZ other) {
        if (other == GrpcPtzControl.PtzControlOuterClass.PtzXYZ.getDefaultInstance()) return this;
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        if (other.getZ() != 0) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GrpcPtzControl.PtzControlOuterClass.PtzXYZ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GrpcPtzControl.PtzControlOuterClass.PtzXYZ) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int x_ ;
      /**
       * <code>int32 X = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>int32 X = 1;</code>
       */
      public Builder setX(int value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 X = 1;</code>
       */
      public Builder clearX() {
        
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>int32 Y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>int32 Y = 2;</code>
       */
      public Builder setY(int value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Y = 2;</code>
       */
      public Builder clearY() {
        
        y_ = 0;
        onChanged();
        return this;
      }

      private int z_ ;
      /**
       * <code>int32 Z = 3;</code>
       */
      public int getZ() {
        return z_;
      }
      /**
       * <code>int32 Z = 3;</code>
       */
      public Builder setZ(int value) {
        
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Z = 3;</code>
       */
      public Builder clearZ() {
        
        z_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GrpcPtzControl.PtzXYZ)
    }

    // @@protoc_insertion_point(class_scope:GrpcPtzControl.PtzXYZ)
    private static final GrpcPtzControl.PtzControlOuterClass.PtzXYZ DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GrpcPtzControl.PtzControlOuterClass.PtzXYZ();
    }

    public static GrpcPtzControl.PtzControlOuterClass.PtzXYZ getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PtzXYZ>
        PARSER = new com.google.protobuf.AbstractParser<PtzXYZ>() {
      public PtzXYZ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PtzXYZ(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PtzXYZ> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PtzXYZ> getParserForType() {
      return PARSER;
    }

    public GrpcPtzControl.PtzControlOuterClass.PtzXYZ getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcPtzControl_PtzDirectRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcPtzControl_PtzDirectRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcPtzControl_PtzDirectReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcPtzControl_PtzDirectReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcPtzControl_PtzXYZ_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcPtzControl_PtzXYZ_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ptz_control.proto\022\016GrpcPtzControl\"X\n\020P" +
      "tzDirectRequest\022#\n\003xyz\030\001 \001(\0132\026.GrpcPtzCo" +
      "ntrol.PtzXYZ\022\r\n\005speed\030\002 \001(\005\022\020\n\010deviceid\030" +
      "\003 \001(\t\"!\n\016PtzDirectReply\022\017\n\007message\030\001 \001(\t" +
      "\")\n\006PtzXYZ\022\t\n\001X\030\001 \001(\005\022\t\n\001Y\030\002 \001(\005\022\t\n\001Z\030\003 " +
      "\001(\0052]\n\nPtzControl\022O\n\tPtzDirect\022 .GrpcPtz" +
      "Control.PtzDirectRequest\032\036.GrpcPtzContro" +
      "l.PtzDirectReply\"\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GrpcPtzControl_PtzDirectRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GrpcPtzControl_PtzDirectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcPtzControl_PtzDirectRequest_descriptor,
        new java.lang.String[] { "Xyz", "Speed", "Deviceid", });
    internal_static_GrpcPtzControl_PtzDirectReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GrpcPtzControl_PtzDirectReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcPtzControl_PtzDirectReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_GrpcPtzControl_PtzXYZ_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GrpcPtzControl_PtzXYZ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcPtzControl_PtzXYZ_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
